name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via Git Pull (HTTPS)
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e
            sudo mkdir -p /var/www/html
            sudo chown -R $EC2_USER:$EC2_USER /var/www/html
            cd /var/www/html

            # Clone repo if not exists
            if [ ! -d "ci-cd-with-html" ]; then
              git clone https://github.com/kavish28081997/ci-cd-with-html.git
            else
              cd ci-cd-with-html
              git pull
            fi
          EOF

          



